In [20]:
import numpy as np
from sklearn.model_selection import train_test_split

###### Datas

In [21]:

# Part 1: Basic splitting
X = np.arange(1, 21).reshape(10, -1)
y = np.zeros(10)
y[7:] = 1

#### 1 - Split the data using train_test_split with shuffle=False. The test set represents 20% of the total size of the data set. Print X_train, y_train, X_test, y_test. Compute the proportion of class 1 on the train set and test set.

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)
print("\nX_test:")
print(X_test)
print("\ny_test:")
print(y_test)

train_prop = np.mean(y_train)
test_prop = np.mean(y_test)

print(f"\nProportion of class 1 in train set: {train_prop:.3f}")

X_train:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]

y_train:
[0. 0. 0. 0. 0. 0. 0. 1.]

X_test:
[[17 18]
 [19 20]]

y_test:
[1. 1.]

Proportion of class 1 in train set: 0.125


#### 2 - Having a train set with different properties than the test set is not recommended. The analogy of the exam (https://www.youtube.com/watch?v=_vdMKioCXqQ) helps to understand this point: if the questions you have at the exam are completely different from what you prepared for you are not evaluated on what you learn. The training set has to be representative of the data set. Now, split the data in a train set and test set, but keep the proportion of class 1 nearly constant. The parameter shuffle in theory works as it relies on a random sampling. The parameter stratify will always split the data and keep the same proportion of class 1 in the train set and test set. Using the parameter stratify split the data below and print the proportion of class 1 in the train set and train set.

In [23]:
print("\nPart 2: Stratified splitting")
X = np.arange(1, 201).reshape(100, -1)
y = np.zeros(100)
y[70:] = 1

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

train_prop = np.mean(y_train)
test_prop = np.mean(y_test)

print(f"Proportion of class 1 in train set: {train_prop:.2f}")
print(f"Proportion of class 1 in test set: {test_prop:.2f}")


Part 2: Stratified splitting
Proportion of class 1 in train set: 0.30
Proportion of class 1 in test set: 0.30
