In [29]:
import numpy as np
from sklearn.impute import SimpleImputer

#### 1 - Fit the SimpleImputer on the data. Print the statistics_. Check that the statistics match np.nanmean(train_data, axis=0).

In [30]:
train_data = np.array([[7, 6, 5],
                       [4, np.nan, 5],
                       [1, 20, 8]])
# For this example :
# 7 + 4 + 1 / 3 = 4
# 6 + 20 / 2 = 13
# 5 + 5 + 8 / 3 = 4
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean').fit(train_data)
print("Imputer statistics (means of columns):", imp_mean.statistics_)

Imputer statistics (means of columns): [ 4. 13.  6.]


#### 2 - Fill the missing values in train_data using the fitted imputer and transform.

In [31]:
# After the SimpleImputer
# Each np.nan values = column mean
train_data_imputed = imp_mean.transform(train_data)
print("Imputed train_data:\n", train_data_imputed)


Imputed train_data:
 [[ 7.  6.  5.]
 [ 4. 13.  5.]
 [ 1. 20.  8.]]


#### 3 - Fill the missing values in test_data using the fitted imputer and transform.

In [32]:
test_data = np.array([[np.nan, 1, 2],
                      [7, np.nan, 9],
                      [np.nan, 2, 4]])

test_data_imputed = imp_mean.transform(test_data)
print("Imputed test_data:\n", test_data_imputed)

Imputed test_data:
 [[ 4.  1.  2.]
 [ 7. 13.  9.]
 [ 4.  2.  4.]]
