In [22]:
import numpy as np
from sklearn.preprocessing import StandardScaler


#### 1 - Fit the StandardScaler on the data and scale X_train using fit_transform. Compute the mean and std on axis 0.

In [23]:
# Define the training dataset
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

# Initialize the StandardScaler
scaler = StandardScaler()
# Train datas
X_train_scaled = scaler.fit_transform(X_train)

mean = scaler.mean_ 
std = np.sqrt(scaler.var_)

print("Scaled X_train:\n", X_train_scaled)
print("Mean of X_train:", mean)
print("Standard Deviation of X_train:", std)


Scaled X_train:
 [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
Mean of X_train: [1.         0.         0.33333333]
Standard Deviation of X_train: [0.81649658 0.81649658 1.24721913]


#### 2 - Scale the test set using the StandardScaler fitted on the train set.

In [24]:
X_test = np.array([[ 2., -1.,  1.],
                   [ 3.,  3., -1.],
                   [ 1.,  1.,  1.]])

X_test_scaled = scaler.transform(X_test)

print("Scaled X_test:\n", X_test_scaled)


Scaled X_test:
 [[ 1.22474487 -1.22474487  0.53452248]
 [ 2.44948974  3.67423461 -1.06904497]
 [ 0.          1.22474487  0.53452248]]
