In [207]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

#### 1 - Using train_test_split, split the data set in a train set, and test set (20%). Use random_state=43 for results reproducibility.

###### Datas

In [208]:

diabetes = load_diabetes(as_frame=True)
X, y = diabetes.data, diabetes.target

#### 1 - Using train_test_split, split the data set in a train set, and test set (20%). Use random_state=43 for results reproducibility.



In [209]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=43)
print("y_train.values[:10]")
print(y_train.values[:10])
print("y_test.values[:10]")
print(y_test.values[:10])

y_train.values[:10]
[202.  55. 202.  42. 214. 173. 118.  90. 129. 151.]
y_test.values[:10]
[ 71.  72. 235. 277. 109.  61. 109.  78.  66. 192.]


#### 2 - Fit the Linear Regression on all the variables. Give the coefficients and the intercept of the Linear Regression. What is the equation ?

In [210]:
model = LinearRegression().fit(X_train, y_train)
expected_order = ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']
X = X[expected_order]

coef_list = [(feature, coef) for feature, coef in zip(expected_order, model.coef_)]
coef_list.append(('intercept', model.intercept_))

print("\nQuestion 2:")
print("Coefficients and Intercept:")
print(coef_list)
y_pred_test = model.predict(X_test).reshape(-1, 1)


Question 2:
Coefficients and Intercept:
[('age', np.float64(-60.39984809333619)), ('sex', np.float64(-226.0835904426927)), ('bmi', np.float64(529.3849571887342)), ('bp', np.float64(259.9619941214206)), ('s1', np.float64(-859.0930093348028)), ('s2', np.float64(504.6869733896189)), ('s3', np.float64(157.41085788032757)), ('s4', np.float64(226.29313435521055)), ('s5', np.float64(840.7840406049223)), ('s6', np.float64(34.71226555571722)), ('intercept', np.float64(152.0532454782767))]


In [211]:
print("\nQuestion 3:")
print("predictions_on_test[:10]")
print(y_pred_test[:10])


Question 3:
predictions_on_test[:10]
[[111.74267934]
 [ 98.41608992]
 [168.36714629]
 [255.06351455]
 [168.44138847]
 [117.60698984]
 [198.8733865 ]
 [126.2932775 ]
 [117.72876579]
 [224.82776308]]


#### 3 - MSE

In [212]:
def mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

y_pred_train = model.predict(X_train)
mse_train = mse(y_train, y_pred_train)
mse_test = mse(y_test, y_pred_test.flatten())

print("\nQuestion 4:")
print(f"MSE on train set: {mse_train:.6f}")
print(f"MSE on test set: {mse_test:.6f}")


Question 4:
MSE on train set: 2888.324598
MSE on test set: 2858.291506
