In [12]:
import numpy as np
from sklearn.model_selection import train_test_split

#### Datas

In [13]:
X = np.arange(1, 21).reshape(10, -1)
y = np.arange(1, 11)

#### 1 - Split the data using train_test_split with shuffle=False. The test set represents 20% of the total size of the data set. Print X_train, y_train, X_test, y_test.

In [14]:
# Used to split, datas_tests && datas_training
# test_size = 0.2 ===
# 20 % datas_tests && 80% datas_training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Print the results
print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)
print("\nX_test:")
print(X_test)
print("\ny_test:")
print(y_test)

X_train:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]

y_train:
[1 2 3 4 5 6 7 8]

X_test:
[[17 18]
 [19 20]]

y_test:
[ 9 10]
