In [34]:
import numpy as np

In [35]:
# Mersenne Twister algoritm
# Good practice using random.seed 
np.random.seed(888)
# NumPy recommands numpy.random.default_rng()

In [36]:
normal_array = np.random.randn(100)
print("Array", normal_array)

Array [-1.76200874e-01  1.88876361e-01  8.26747180e-01 -3.24473146e-02
 -6.52499418e-01 -1.05339382e-01  2.17776116e-01  5.87281504e-01
  1.00237892e-01 -1.09994668e+00 -2.55305389e-01  4.05304381e-01
  1.62663953e-01  1.04163462e+00  2.24324184e-01  6.99304449e-01
 -8.65543512e-01 -1.39346831e+00 -2.36687913e-01 -7.57041911e-01
  1.31429195e+00 -9.77385899e-01 -3.59032576e-01  1.16141585e-01
 -3.51081138e-01 -4.39838344e-01 -4.90995473e-02 -4.31596770e-01
 -1.08875099e+00 -2.31088106e+00 -1.86236420e+00  2.34708674e-01
 -8.95585921e-01 -5.40834525e-01 -4.02399061e-01  2.31458561e-02
  1.77688506e-01 -5.73309272e-01 -3.38392138e-01 -2.64422114e-03
  1.44930339e+00  1.36605641e+00  2.69187461e+00  6.76065035e-01
 -1.06098418e+00  1.31845313e-01  1.71934297e-01  8.88062794e-02
  1.03963016e+00 -1.37846942e-01 -3.69232844e-01  3.19587912e+00
  1.11457451e+00 -2.59516296e-01  1.48370897e+00 -1.57049065e+00
  9.78899330e-01  1.76070681e+00  3.53121953e-01 -3.08510762e-01
 -1.40481067e+00 -6

In [37]:
# Create 2d Array with 8 row, 8 column
# Value 1 -> 11
# Syntaxe np.random.randint(low, high=None, size=None)
uniform_2d = np.random.randint(1, 11, (8, 8))
print("Array 2d", uniform_2d)

Array 2d [[ 9  8  4  6  9  1  3  2]
 [ 3  9  9  5  4  7  2  8]
 [ 5  6  9  1  1  6  8  7]
 [ 7  1  4  1 10  4  3  5]
 [ 5 10  1 10  7 10  6  1]
 [ 6  8  7  4  6 10  3  5]
 [ 4 10  7  9  9 10  9  9]
 [ 5  3  2 10  8  5  5  3]]


In [38]:
#Create 3d Array
#Matrice Betwen 1 - 17 - 4 matrices, 2 lines, 5 elements
uniform_3d = np.random.randint(1, 18, (4, 2, 5))

In [39]:
print("Array 3d", uniform_3d)

Array 3d [[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]
